project:
  type: website
  output-dir: docs

website:
  title: "Academic Portfolio"
  favicon: images/ColgateC.png
  sidebar:
    logo: images/ColgateSeal.png
    style: "docked"
    collapse-level: 1
    search: false
    contents:
      - href: index.qmd
        text: " Home"
        